version: "3.8"

services:
  merchandise-service:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: merchandise-service
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5424;Database=merchandise-service;Username=postgres;Password=merchandiseServicePassword"
    depends_on:
      - merchandise-service-db

  merchandise-service-db:
    image: postgres:latest
    ports:
      - "5424:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchandiseServicePassword
      POSTGRES_DB: merchandise-service
#    volumes:
#      - ./volumes/merchandise-service-db/dbdata:/var/lib/postgresql/data
    command: "-c log_statement=all"
    